/*
* Copyright (C) 2017 The Pixel Experience Project
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
package com.android.internal.util.ion;

public class OverlayUtils {
    public static String[] AllPackages = {
            "com.android.system.theme.light",
            "com.android.system.theme.dark",
            "com.android.system.theme.black",
            "com.android.systemui.custom.theme.dark",
            "com.android.systemui.custom.theme.black",
            "com.android.gboard.theme.dark",
            "com.android.gboard.theme.light",
            "com.android.wellbeing.theme.dark",
            "com.android.documentsui.theme.dark",
            "com.android.documentsui.theme.black",
            "org.pixelexperience.overlay.hidecutout",
            "com.accents.red",
            "com.accents.pink",
            "com.accents.purple",
            "com.accents.deeppurple",
            "com.accents.indigo",
            "com.accents.blue",
            "com.accents.lightblue",
            "com.accents.cyan",
            "com.accents.teal",
            "com.accents.green",
            "com.accents.lightgreen",
            "com.accents.lime",
            "com.accents.yellow",
            "com.accents.amber",
            "com.accents.orange",
            "com.accents.deeporange",
            "com.accents.brown",
            "com.accents.grey",
            "com.accents.bluegrey",
            "com.accents.black",
            "com.accents.white",
            "com.accents.userone",
            "com.accents.usertwo",
            "com.accents.userthree",
            "com.accents.userfour",
            "com.accents.userfive",
            "com.accents.usersix",
            "com.accents.userseven",
            "com.accents.maniaamber",
            "com.accents.coldyellow",
            "com.accents.newhouseorange",
            "com.accents.warmthorange",
            "com.accents.burningred",
            "com.accents.candyred",
            "com.accents.palered",
            "com.accents.hazedpink",
            "com.accents.bubblegumpink",
            "com.accents.trufilpink",
            "com.accents.duskpurple",
            "com.accents.illusionspurple",
            "com.accents.spookedpurple",
            "com.accents.notimppurple",
            "com.accents.dreamypurple",
            "com.accents.footprintpurple",
            "com.accents.obfusbleu",
            "com.accents.frenchbleu",
            "com.accents.coldbleu",
            "com.accents.heirloombleu",
            "com.accents.paleblue",
            "com.accents.holillusion",
            "com.accents.stock",
            "com.accents.seasidemint",
            "com.accents.movemint",
            "com.accents.extendedgreen",
            "com.accents.diffdaygreen",
            "com.accents.jadegreen",
            "com.accents.oneplusred",
            "com.accents.usereight",
            "com.accents.usernine",
            "com.android.systemui.qstile.default",
            "com.android.systemui.qstile.circle",
            "com.android.systemui.qstile.circlegradient",
            "com.android.systemui.qstile.circletrim",
            "com.android.systemui.qstile.cookie",
            "com.android.systemui.qstile.cosmos",
            "com.android.systemui.qstile.diamond",
            "com.android.systemui.qstile.divided",
            "com.android.systemui.qstile.dottedcircle",
            "com.android.systemui.qstile.dualtonecircle",
            "com.android.systemui.qstile.dualtonecircletrim",
            "com.android.systemui.qstile.gear",
            "com.android.systemui.qstile.hexagon",
            "com.android.systemui.qstile.ink",
            "com.android.systemui.qstile.inkdrop",
            "com.android.systemui.qstile.mountain",
            "com.android.systemui.qstile.neonlike",
            "com.android.systemui.qstile.ninja",
            "com.android.systemui.qstile.oreo",
            "com.android.systemui.qstile.oreocircletrim",
            "com.android.systemui.qstile.oreosquircletrim",
            "com.android.systemui.qstile.oxygen",
            "com.android.systemui.qstile.pokesign",
            "com.android.systemui.qstile.roundedsquare",
            "com.android.systemui.qstile.square",
            "com.android.systemui.qstile.squircle",
            "com.android.systemui.qstile.squircletrim",
            "com.android.systemui.qstile.squaremedo",
            "com.android.systemui.qstile.star",
            "com.android.systemui.qstile.teardrop",
            "com.android.systemui.qstile.triangles",
            "com.android.systemui.qstile.wavey",
            "com.android.systemui.qsheader.black",
            "com.android.systemui.qsheader.grey",
            "com.android.systemui.qsheader.lightgrey",
            "com.android.systemui.qsheader.accent",
            "com.android.systemui.qsheader.transparent",
            "com.android.system.switch.ion",
            "com.android.system.switch.stock",
            "com.android.system.switch.md2",
            "com.android.system.switch.oneplus",
            "com.android.system.switch.one",
            "com.android.system.switch.two",
            "com.android.system.switch.three",
            "com.android.system.switch.four",
            "com.android.system.switch.five",
            "com.android.system.switch.six",
            "com.android.system.switch.seven",
            "com.android.system.switch.eight",
            "com.android.system.switch.nine",
            "com.android.facelock.theme.dark",
    };
}
